export const SHOPPING_LIST = ['MILK', 'BREAD', 'HAM', 'CHEESE', 'WATER'] as const
export const BOOKS = [
    'SAPIENS BY YUVAL NOAH HARARI',
    'THE THEORY OF EVERYTHING BY STEPHEN HAWKING',
    'A WILD SHEEP CHASE BY HARUKI MURAKAMI',
    'CLEAN CODE BY ROBERT MARTIN'
] as const